### PR TITLE
Typo: eldritch -> Eldritch.

### PR DESCRIPTION
**Pull request by cstrobbe**
;-)

### CODE REVIEW

**Comment by colinbdclark** [comment]
Implausible though it is, Eldritch actually spelled his name with a lower case "e" when he wrote _Boring Formless Nonsense_. I don't know for sure, but I suspect his driver's license might also have a lower case first name (I've never asked him, but I should). 

If you look at the image of the book cover [from Bloomsbury](http://www.bloomsbury.com/us/boring-formless-nonsense-9781441122131/), you can see its lower case-ness. Interestingly Bloomsbury themselves list is under the name "Eldritch," though [Amazon lists it](https://www.amazon.ca/Boring-Formless-Nonsense-Experimental-Aesthetics/dp/1441122133?ie=UTF8&*Version*=1&*entries*=0) in lower case. I gather that since publishing the book, Eldritch has started to capitalize his first name, presumably to head off exactly this sort of confusion.

@waharnum, as our resident ex-librarian, do you recommend citing the book with lower case "eldritch" or upper?

**Comment by colinbdclark** [comment]
Oh, and I forgot to mention--thanks for reading, @cstrobbe. I'm quite impressed to see that you notice my little side project here and took the time to contribute a fix. :smile:  Most of the main action is currently happening in a series of branches, for which there are related pull requests. It's slowly starting to take shape.

**Comment by cstrobbe** [comment]
I hadn't noticed the book cover. When you "look inside" on Amazon to check the page with bibliographic data, there are two instances of "eldritch" and one of "Eldritch". When I was studying library & information science, I was told that this page with copyright & bibliographic data is what you base your catalogue record on, but even this page is inconsistent. 
Ah, the curse of e.e. cummings ;-)

**Comment by waharnum** [comment]
@cstrobbe (another ex-librarian? what are the odds? ;)) correctly points to the Cataloguing In Publication data via Amazon as showing capitalization for the derived author name, but the title statement replicates the lowercase (title statements usually aim to preserve exactly the text of the title, including punctuation, spelling, etc).

The main purpose of an annotated bibliography, IMO, is to allow an interested reader to locate the work in question. Either eldritch or Eldritch seem acceptable to me for these purposes. Since it appears Eldritch is now going with the capitalization, it would be acceptable to use his current preference, which might avoid potential misunderstandings.

**Comment by cstrobbe** [comment]
@waharnum Actually, an ex-would-be-librarian ;-)

**Comment by colinbdclark** [comment]
I've asked the good Dr. Priest what his preference is and will report back with his response.

**Comment by colinbdclark** [comment]
From the author: "For the record…The lower case is correct. And while it’s not indicated on my driver’s license (which is all upper case), it is on my birth certificate. I do like the lower case 'e'; however, I’m capitalizing 'Eldritch' these days. People seem to get unduly irritated by the lowercase, and (as I’ve learned) it’s just not worth the effort to insist on it. If I did I insist I’d probably want that lower case be respected when citing BFN. I really meant it back then."

Since eldritch is a friend and a writer I greatly respect, I'll stick with the lower case spelling of his name here.

Thanks for an interesting conversation, thought, @cstrobbe! This was great.

**Pull request closed without merging**
